### ISSUE TITLE
Add more links and columns

### ISSUE THREAD

**Issue by stpnwf** [migueravila/Bento#90]
How can I add more links and more columns?
I am using the list layout and it is very nice, but I would like to be able to create another column or two and to have more than just 4 links. Is this a planned feature? If not, could I get some pointers about how I could do this?

Also I have this issue (out of the box) where only the `firstlistsContainer` or `firstButtonsContainer` is displayed when the browser window gets narrow (not full screen). I would expect `secondListsContainer` to be displayed below it and be revealed upon scrolling instead. Is this the intended behavior? If not, can this be enabled somehow?

**Comment by lewisdoesstuff** [comment]
I don't believe this is a default feature, unfortunately. 

If you'd like to add another column, you'd have to change the HTML generation in `lists.js` or `buttons.js` to add another column beside it. 

For the second box disappearing when you resize, this is to support smaller (phone) displays. You can remove the media queries from the `app.css` file which should stop it resizing, but this won't stack the boxes, and likely ruin the styling. 

If you want them to be stacked, you can change the media queries part of the CSS to stack the boxes, instead of hiding it.

**Comment by stpnwf** [comment]
Thanks for the reply. I will look into it!

**Comment by Vanortton** [comment]
Estou fazendo um upgrade e resolvo o problema em que "apenas o ou é exibido quando a janela do navegador fica estreita (não em tela cheia). Eu esperaria ser exibido abaixo dele e ser revelado ao rolar em vez disso". Dá uma olhada lá https://github.com/Vanortton/Bento
